apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - workshop-admins-group.yaml
  - workshop-users-group.yaml

patches:
  - target:
      kind: ClusterRoleBinding
      name: self-provisioners
    patch: |
      - op: replace
        path: /subjects
        value:
