apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../default

patches:
  - target:
      group: workspace.devfile.io
      kind: DevWorkspaceTemplate
    patch: |-
      - op: replace
        path: /spec/components/0/container/args
        value:
          - "/bin/bash"
          - "-c"
          - |
            #!/bin/bash
            GIT_REPO=https://github.com/codekow/demo-ai-gitops-catalog.git

            echo "
              echo
              echo 'This terminal has been enhanced.'
              echo See ${GIT_REPO}
            " >> ~/.bashrc

            git clone "${GIT_REPO}" gitops

            echo "
              cd gitops; . scripts/functions.sh; cd ..

            __git_branch(){
              git name-rev --name-only @ 2>/dev/null
            }

            PS1='\e];\s\a\n\e[33m\w \e[36m\$(__git_branch)\e[m$ '

            [ -d .venv ] && . .venv/bin/activate

            " >> ~/.bashrc

            cd gitops
            . scripts/functions.sh

            [ -d .venv ] || pyvenv-3.6 .venv
            
            check_bin busybox
            check_bin rclone
            check_bin restic

            sleep infinity
