apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-config

resources:
  - ../../base
  # - htpasswd-secret.yaml
  - job.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: job-init-htpasswd
    files:
      - htpasswd-secret.yaml
      - job.sh

# Patch cluster specific
patches:
  - path: patch-idp.yaml
    target:
      group: config.openshift.io
      kind: OAuth
      name: cluster
