apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nfs-provisioner

resources:
- https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/deploy

patches:
- patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: nfs-provisioner
  target:
    kind: ClusterRoleBinding
