apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app: minio
  - includeSelectors: false
    pairs:
      app.kubernetes.io/component: minio

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: job-create-minio-root
    files:
      - job.sh

resources:
- data-connector-rb.yaml
- deployment.yaml
- job.yaml
# - link-minio.yaml
- pvc.yaml
- route.yaml
- service.yaml
