apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app: pgadmin4
- includeSelectors: false
  pairs:
    app.kubernetes.io/component: pgadmin4
    app.kubernetes.io/instance: pgadmin4

resources:
- pgadmin4-bc.yml
- pgadmin4-deployement.yml
- pgadmin4-is.yml
- pgadmin4-route.yml
- pgadmin4-svc.yml
