apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: pgadmin4
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: docker.io/dpage/pgadmin4:latest
    from:
      kind: DockerImage
      name: docker.io/dpage/pgadmin4:latest
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
