apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - cluster-admins-group.yaml
  - cluster-admins-rolebinding.yaml
  - cluster-readers-group.yaml
  - cluster-readers-rolebinding.yaml
