apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../components/cluster-configs/autoscale/overlays/gpus
  - ../../../components/operators/gpu-operator-certified/instance/overlays/aws-time-sliced
  - ../../../components/operators/gpu-operator-certified/operator/overlays/stable
  - ../../../components/operators/nfd/instance/overlays/only-nvidia
  - ../../../components/operators/nfd/operator/overlays/stable
