---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: htpasswd-workshop-kludge
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: htpasswd-workshop-kludge
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: htpasswd-workshop-kludge
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: htpasswd-workshop-kludge
subjects:
- kind: ServiceAccount
  name: htpasswd-workshop-kludge
  namespace: openshift-config
